config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :animals
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'swiper/home'
  get 'swiper/my'
  # Defines the root path route ("/")
  root "home#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :posts
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :post
  has_one_attached :pic
end

app/models/post.rb
class Post < ApplicationRecord
  include Discard::Model
  validates :user_id, presence: true
  validates :animal, presence: true
  belongs_to :animal
  belongs_to :user
  has_rich_text :description
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true
  enum :sexuality, %i[ male female unknown ]
  enum :size, %i[ small medium large ]
  enum :status, %i[ pending adopted ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: t('animal.created') }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: t('animal.updated') }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: t('animal.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_animals, only: %i[ show edit new ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = Post.where(user: current_user).kept
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    3.times { @post.pictures.build }
  end

  # GET /posts/1/edit
  def edit
    authorize @post
    (3-@post.pictures.count ).times { @post.pictures.build }
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: t('post.created') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: t('post.updated') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.discard

    respond_to do |format|
      format.html { redirect_to posts_url, notice: t('post.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    def set_animals
      @animals = Animal.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:description, :animal_id, :sexuality, :birth, :size, :status, pictures_attributes: [:id, :pic, :_destroy])
    end
end

app/controllers/swiper_controller.rb
class SwiperController < ApplicationController
  def home
    @posts = Post.not_adopted
    render template: 'swiper/swiper'
  end

  def my
    @posts = Post.all
    render template: 'swiper/swiper'
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/animals/_animal.html.erb
<div id="<%= dom_id animal %>">
  <% if animal.image.attached? %>
    <%= image_tag animal.image, size: '100' %>
  <% end %>
  <%= animal.name %>
</div>

   

app/views/animals/_form.html.erb
<%= form_with(model: animal) do |form| %>
  <% if animal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% animal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= label_tag(:name, t('name')) %>
  <%= form.text_field :name, class: 'form-control' %>
  <%= label_tag(:image, t('image')) %>
  <%= form.file_field :image %>
  <div>
    <%= form.submit t('create'),class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Show this animal", @animal %> |
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/index.html.erb
<h1><%= t('animals')%></h1>

<div id="animals">
  <table class="table">
    <% @animals.each do |animal| %>
      <tr>
        <td><%= render animal %></td>
        <td><%= link_to t('animal.show'), animal, class: 'btn btn-info' %></td>
        <td><%= link_to t('edit'), edit_animal_path(animal), class: 'btn btn-warning' %></td>
        <td><%= button_to t('destroy'), animal, form: { data: { turbo_confirm: t('sure') } }, :method => :delete, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to t('animal.new'), new_animal_path, class: 'btn btn-primary' %>

app/views/animals/new.html.erb
<h1><%= t('animal.new') %></h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to t('animal.back_to_animals'), animals_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/animals/show.html.erb
<%= render @animal %>

<div>
  <%= link_to t('edit'), edit_animal_path(@animal), class: 'btn btn-warning' %> |
  <%= link_to t('animal.back_to_animals'), animals_path, class: 'btn btn-outline-secondary' %>

  <%= button_to t('destroy'), @animal, method: :delete, form: { data: { turbo_confirm: t('sure') } }, class: 'btn btn-danger mt-2' %>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-6 d-flex flex-column justify-content-center align-items-center">
      <h1>Adoptemos y demos <br> unartunidadoportunidad</h1>
      <h2>Ayudemos a conseguir un <br> hogar</h2>
      <div class="d-flex">
        <%= link_to 'Adoptar','#adoptables' ,class: 'btn btn-primary mx-2' %>
        <%= link_to 'Dar en adopción', new_post_path, class: 'btn btn-primary' %>
      </div>
  </div>
  <div class="col-md-6">
    <div class="">
      <%= image_tag "pets.svg", size: '800' %>
    </div>
  </div>
</div>

<div id="adoptables">
  <h1><%= t('pets_waiting_a_home')%></h1>
  <%= turbo_frame_tag :posts, src: '/swiper/home' do %>
    <div class="d-flex justify-content-center">
      <%= image_tag "dog.gif", height: 300 %>
    </div>
  <% end %>
</div>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<div class="b-divider"></div>
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Company, Inc</p>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Omiwomi</span>
    </a>

    <ul class="nav nav-pills">
      <li class="nav-item">
        <%= link_to t('home'), root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
      <% if user_signed_in? %>
        <%= link_to t('my_posts'), posts_path, class: 'nav-link' %>
        <li class="nav-item">
          <%= button_to t('logout'), destroy_user_session_path, method: :delete, class: 'nav-link active' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t('login'), new_user_session_path, class: 'nav-link active' %>
        </li>
      <% end %>
    </ul>
  </header>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Omiwomi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class='container'>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class:"bg-white p-4 border shadow-lg rounded-3") do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label t('photos'), style: "display: block" %>
  <i>Selecciona una o mas fotos de la mascota</i><br>
  <%= form.fields_for :pictures do |picture_model| %>
    <%= picture_model.file_field :pic, class: 'mt-2' %> <br>
    <%= image_tag picture_model.object.pic, width: '100' if picture_model.object.pic.attached? %>
    <hr>
  <% end %>
  <div class="row">
    <div class="col-md-4">
      <%= form.label t('post.sexuality'), style: "display: block" %>
      <%= form.select :sexuality, Post.sexualities.map { |key, value| [t("sexuality.#{key}"), key] }, {}, {class: 'form-select'}%>
    </div>

    <div class="col-md-4">
      <%= form.label t('post.size'), style: "display: block" %>
      <%= form.select :size, Post.sizes.map { |key, value| [t("size.#{key}"), key] }, {}, {class: 'form-select'}%>
    </div>
    <div class="col-md-4">
      <%= form.label t('post.status'), style: "display: block" %>
      <%= form.collection_radio_buttons :status, Post.statuses, :first, :first do |b| %>
      <%=  b.radio_button %>
      <%= t('status.'+b.text) %><br>
      <% end %>
    </div>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <i>Cuéntanos un poco mas acerca de la mascota. Ej: "Le gusta jugar", "Es guardián/a", "Se lleva bien/mal con otros animales", "Su nombre es... (si tiene)", etc. </i>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.collection_radio_buttons :animal_id, @animals, :id, :name, boolean_style: :inline do |check| %>
      <%= image_tag check.object.image, size: 200 %>
      <%= check.radio_button %>
      <%= check.object.name %>
    <% end %>
  </div>

  <div class="mt-2">
    <%= form.submit t('post.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
    <div class="card card-post">
      <%= link_to post_path(post), target: '_top', class:'text-decoration-none link-image' do %>
        <%= image_tag url_for(post.pictures.first.pic), style: 'max-width: 300px'%>
      <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<h1><%= t('post.edit')%></h1>

<%= render "form", post: @post %>
<br>

app/views/posts/index.html.erb
<h1><%= t('my_posts')%></h1>

<%= turbo_frame_tag :posts, src: 'swiper/my' do %>
  <div class="d-flex justify-content-center">
    <%= image_tag "dog.gif", height: 300 %>
  </div>
<% end %>

<%= link_to t("post.new"), new_post_path, class: 'btn btn-primary mt-2' %>

app/views/posts/new.html.erb
<h1><%= t('post.new')%></h1>

<%= render "form", post: @post %>

<div>
  <%= link_to t('cancel'), posts_path, class: 'btn btn-outline-secondary mt-2' %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-4">
    <label style="display: block"><%= t('post.sexuality') %>:</label>
    <%= t("sexuality.#{@post.sexuality}") %>
  </div>
  <div class="col-md-4">
    <label style="display: block"><%= t('post.size') %>:</label>
    <%= t("size.#{@post.size}") %>
  </div>
  <div class="col-md-4">
    <label style="display: block"><%= t('post.status') %>:</label>
    <%= t("status.#{@post.status}") %>
  </div>
</div>
  <label style="display: block"><%= t('post.description') %>:</label>
  <%= @post.description %>
  <label style="display: block"><%= t('post.pictures') %>:</label>
  <% if @post.pictures.any? %>
    <% @post.pictures.each do |picture| %>
      <%= image_tag picture.pic, width: '350' if picture.pic.attached? %>
    <% end %>    
  <% else %>
    <i> No hay fotos para mostrar </i>
  <% end%>


<hr>
<div class="mt-2">
  <%= link_to t("post.edit"), edit_post_path(@post), class: 'btn btn-outline-warning' %> |
  <%= link_to t("post.back"), posts_path, class: 'btn btn-outline-secondary' %>

  <%= button_to t("post.destroy"), @post, method: :delete, class: 'btn btn-danger mt-2' %>
</div>

app/views/swiper/swiper.html.erb
<%= turbo_frame_tag :posts do %>
  <div class="swiper swiper_posts" data-controller='swiper'>
    <div class="swiper-wrapper">
      <% @posts.each do |post| %>
        <div class="swiper-slide">
          <%= render post %>
        </div>
      <% end %>
    </div>

    <div class="swiper-pagination"></div>

    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- If we need scrollbar -->
    <div class="swiper-scrollbar"></div>
  </div>
<% end %>